### PR TITLE
Closes #90 Adopt feedback for eligibility by {group} charts

### LINKED ISSUE #90: QTL0001 Criteria by site/country barcharts are broken/too zoomed in
## Current Behavior

-  Criteria/Site and Criteria/Country charts are completely unusable as combinations of criteria were plotted on y-axis, incorrect delimiter was being used.
- Additional request to add swapped version of those two charts (site/criteria, country/criteria) where y-axis and fill columns are essentially swapped.
- Cleanup premature discontinuation visualizations (mostly datasim data issue) such that our filters on `compyn == "N"` align across the visualizations and that the numerator found at the QTL Overview match the respective visualizations below it

## Expected Behavior

- Each inc/exc criteria should be plotted individually such that each box represents a singular count of a particular criterium being violated.
- New charts with swapped axis/fill should be minimally invasive to codebase
- Visualizations for premature discontinuation should be consistent across all tables and figures

## Possible Solution
-  Use appropriate delimiter in data and function to appropriately extract the inc/exc criteria
- Add function argument to `criteria_groupBar()` to swap y-axis and fill col depending on which version of the barchart is needed
- Ensure the data model is consistent when feeding in summarized data (qtl overview) and participant level dataset (with filter conditions) on the barcharts/listings

## QC Approach

[X] Update existing Qualification/Unit Tests 
[X] New Unit Tests

### PR DESCRIPTION
**Pull request by zdz2101**
## What Changed

- Updated criteria parsing to use the appropriate delimiter so inclusion/exclusion criteria are split and counted at the individual criterion level.
- Extended the existing criteria bar chart function with a swap-axes argument so the new Site/Criteria and Country/Criteria charts reuse the same implementation.
- Added the swapped chart outputs to the QTL report.
- Standardized discontinuation visualizations and listing logic around premature discontinuations by aligning on participants with `compyn == "N"`.
- Excluded Completed/Ongoing records from discontinuation reason visualizations so the displayed numerators match the discontinuation-focused overview and downstream charts.
- Cleaned up example/report data handling to keep discontinuation reasons consistent with the visualization logic.

## Impact

- Eligibility criteria charts are now interpretable and actionable.
- The requested alternate chart orientation is available with minimal codebase impact.
- Premature discontinuation counts are consistent across overview metrics, charts, and listings.
- Closes #90 

## QC Approach

- [x] Updated existing Qualification/Unit Tests
- [x] Added new Unit Tests

## Validation Notes

- Updated coverage for eligibility/discontinuation behavior.
- Added test coverage for the swapped criteria chart behavior.
- Confirmed the criteria chart titles/tooltips reflect the corrected criteria-level breakdown.

### CODE REVIEW

File: R/criteria_groupBar.R [hunk 1]
```diff
@@ -13,9 +13,8 @@ criteria_groupBar <- function(df, varGroupID, strGroupLabel) {
 
   # Create GG object
   df_counts <- df %>%
-    filter(!is.na(ietestcd_concat) | Source == "Eligibility IPD only") %>%
-    tidyr::separate_longer_delim(ietestcd_concat, ";;;") %>%
-    mutate(ietestcd_concat = ifelse(Source == "Eligibility IPD only", "PD without EDC I/E", ietestcd_concat))%>%
+    filter(!is.na(ietestcd_concat)) %>%
```
[the remark this answers is not in the document]
Comment (zdz2101) [reply R/criteria_groupBar.R]: @samussiah what do you think of copilots suggestion

[the remark this answers is not in the document]
Comment (samussiah) [reply R/criteria_groupBar.R]: Looking at the `EXCLUSION` mapping, [IE criteria are `,`-delimited](https://github.com/Gilead-BioStats/gsm.mapping/blob/v1.1.2/inst/workflow/1_mappings/EXCLUSION.yaml#L51-L61) and [PDs are `;;;`-delimited](https://github.com/Gilead-BioStats/gsm.mapping/blob/v1.1.2/inst/workflow/1_mappings/EXCLUSION.yaml#L70-L81).  But we're only parsing IE criteria here so `,`'s the way to go, right?

[the remark this answers is not in the document]
Comment (samussiah) [reply R/criteria_groupBar.R]: Looks like the IE criteria delimiter got changed in [this commit](https://github.com/Gilead-BioStats/gsm.mapping/commit/e8b4e8bc7d22628c9d75d38c70909cd7985a2541).  Honestly, it might be easiest to just plot the IE domain where `ie_violation=='Y'` to avoid the delimiter issue entirely.

[the remark this answers is not in the document]
Comment (zdz2101) [reply R/criteria_groupBar.R]: haha more of my shortcomings forgetting code I wrote, the "trouble" if there really is any is that I use just the `Mapped_EXCLUSION` domain to create all 5 plots and the listing, so pulling in an extra data source just for 2 plots feels.... worth it/not worth it? Im pretty indifferent

[the remark this answers is not in the document]
Comment (samussiah) [reply R/criteria_groupBar.R]: very true - let's just go with comma-delimited and file an issue to evaluate directly passing in the IE data in a future release.

**Review by samussiah — APPROVED** [review]

File: R/discontinuation_groupBar.R [hunk 2]
```diff
@@ -3,21 +3,27 @@
...
 #' @param strGroupLabel A `string` to label the `varGroupID` in reference to axes, legend, footnotes.
-#' @param varStatus A variable indicating participant study status, defaults to `compyn`.
-#' @param valuesDiscontinued A vector of values in `varStatus` considered discontinued, defaults to `c("N")`.
+#' @param varStatus A variable indicating participant study status, defaults to `compreas`.
+#' @param valuesDiscontinued A vector of values in `varStatus` considered premature discontinuations, defaults to a string of known reasons.
 #'
 #' @returns A `plotly` object
 #'
 #' @export
-discontinuation_groupBar <- function(df, varGroupID, strGroupLabel, varStatus = compyn, valuesDiscontinued = c("N")) {
```
Comment (zdz2101) [inline R/discontinuation_groupBar.R:12]: @samussiah Realized I was probably just constructing this incorrectly, on top of the datasim data not fully aligning with the shape of actual real study `STUDCOMP`s, this new swap from compyn to compreas and valuesDisc from Y/N/'' to {actual reasons} is a much clearer/direct translation of what we mean

File: data-raw/Example_QTL.R [hunk 3]
```diff
@@ -51,9 +51,12 @@ all_reportingMetrics <- reporting[[length(reporting)]]$Reporting_Metrics
 all_reportingGroups <- reporting[[length(reporting)]]$Reporting_Groups
 
 report_listings <- list(qtl0001 = mapped[[length(mapped)]]$Mapped_EXCLUSION,
-                        qtl0002 = left_join(mapped[[length(mapped)]]$Mapped_STUDCOMP,
-                                            select(mapped[[length(mapped)]]$Mapped_SUBJ, subjid, country),
-                                            by = "subjid"))
+                        qtl0002 = left_join(
```
Comment (samussiah) [inline data-raw/Example_QTL.R]: This might make more sense as a right join since `STUDCOMP` is typically a subset of `SUBJ`.

File: R/discontinuation_groupBar.R [hunk 4]
```diff
@@ -3,21 +3,27 @@
...
+discontinuation_groupBar <- function(df,
+                                     varGroupID,
+                                     strGroupLabel,
+                                     varStatus = compreas,
+                                     valuesDiscontinued = c('WITHDRAWAL BY SUBJECT', 'NON-COMPLIANCE WITH STUDY DRUG', 'PROTOCOL VIOLATION', 'PHYSICIAN DECISION',
```
Comment (samussiah) [inline R/discontinuation_groupBar.R]: This list of discontinuation reasons needs to be exhaustive which is more configuration for us and more prone to error. I would stick with your original parameterization.  We really need to standardize study disposition earlier in the pipeline but it's easy enough to just specify the discontinuation flag value.

**Review by samussiah — CHANGES_REQUESTED** [review]
Charts are looking good! I'd suggest staying with discontinuation flag rather than discontinuation reason for simplicity. Probably want to subset the listing on premature discontinuation. Also, the _Reasons_ chart is displaying `compreas` in the legend:

Image

File: inst/report/Report_QTL.Rmd [hunk 5]
```diff
@@ -71,7 +71,7 @@ if("Analysis_qtl0002" %in% dfResults$MetricID) {
 ```
 
 ```{r echo=FALSE}
-toggle_toc <- system.file('report', 'lib', 'toggleTOC.js', package = "gsm.kri")
+toggle_toc <- system.file('report', 'lib', 'toggleTOC.js', package = "gsm.qtl")
 ```
```
[the remark this answers is not in the document]
Comment (zdz2101) [reply inst/report/Report_QTL.Rmd:82]: good point, will remove

File: R/discontinuation_groupBar.R (hunk 4 above)
Comment (zdz2101) [reply R/discontinuation_groupBar.R]: swapped back to compyn and "N"

File: R/discontinuation_groupBar.R [hunk 6]
```diff
@@ -3,21 +3,27 @@
...
+                                                            'WITHDREW CONESENT', 'DEATH', 'LOST TO FOLLOW UP', 'LOST TO FOLLOW-UP',
```
[the remark this answers is not in the document]
Comment (zdz2101) [reply R/discontinuation_groupBar.R]: swapped to compyn and "N"

File: data-raw/Example_QTL.R [hunk 7]
```diff
@@ -33,10 +33,37 @@ reporting_wf <- gsm.core::MakeWorkflowList(strNames = c("Results", "Groups", "Me
 
 lRaw <- map_depth(ie_data, 1, gsm.mapping::Ingest, mappings_spec)
 mapped <- map_depth(lRaw, 1, ~ gsm.core::RunWorkflows(mappings_wf, .x))
+# Cleanup discontinuation reasons instead of modifiying gsm.datasim
+mapped <- map(mapped, ~ {
```
Comment (zdz2101) [inline data-raw/Example_QTL.R:38]: @samussiah this is the equivalent of what needs to be cleaned up for datasim to get it closer to "aligned" real study data

Comment (samussiah) [reply data-raw/Example_QTL.R:38]: Yeah, this looks a lot closer to the actual study data.

**Comment by zdz2101** [comment]
> ## [{qcthat}](https://gilead-biostats.github.io/qcthat/) Report: User Acceptance
> No issues are awaiting UAT.
> 
> This report was generated by [this GitHub Actions run](https://github.com/Gilead-BioStats/gsm.qtl/actions/runs/23863671941/job/69576803582).
> 
> _Last updated: 2026-04-01 18:14:22 UTC_
> 
> Session Info



> ## [{qcthat}](https://gilead-biostats.github.io/qcthat/) Report: User Acceptance
> No issues are awaiting UAT.
> 
> This report was generated by [this GitHub Actions run](https://github.com/Gilead-BioStats/gsm.qtl/actions/runs/23863671941/job/69576803582).
> 
> _Last updated: 2026-04-01 18:14:22 UTC_
> 
> Session Info

@jonthegeek  Did I set up #93 incorrectly ?

**Comment by jonthegeek** [comment]
> @jonthegeek Did I set up #93 incorrectly ?

Create UAT issues with `qcthat::ExpectUserAccepts()`. Manually created UAT issues don't do anything. A child of #90 will be auto-created via that expectation, and that expectation failing is what qcthat sees.

File: tests/testthat/test-exported-qtl-reporting.R [hunk 8]
```diff
@@ -234,10 +234,10 @@ test_that("Report_QTL renders a valid HTML report for single metric input (#4, #
   expect_valid_html_output(out)
 })
 
-test_that("Example QTL Report for 2026Q1 meets ui/ux/aesthetics expectations (#93)", {
+test_that("Example QTL Report for 2026Q1 meets ui/ux/aesthetics expectations (#94)", {
```
Comment (jonthegeek) [inline tests/testthat/test-exported-qtl-reporting.R]: You aren't testing #94; you created #94 to test #90. This should be #90.

File: tests/testthat/test-exported-qtl-reporting.R [hunk 9]
```diff
@@ -234,10 +234,10 @@ test_that("Report_QTL renders a valid HTML report for single metric input (#4, #
...
   qcthat::ExpectUserAccepts(
     "Example QTL Report for 2026Q1 meets ui/ux/aesthetics expectations.",
-    intIssue = 93,
+    intIssue = 94,
```
Comment (jonthegeek) [inline tests/testthat/test-exported-qtl-reporting.R]: This should also be #90.

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Don't manually create UAT tests, and don't reference those manually created UAT tests. The test should mention the issue that you're testing, not the sub-issue. Never manually create a test that is tagged `qcthat-uat`.

I definitely need better instructions, and to have qcthat notice when things are weird...

File: inst/report/QTL0002.Rmd [hunk 10]
```diff
@@ -45,14 +45,25 @@ reasons_groupBar(df = qtl0002_params$dfListing, varGroupID = invid, varCompreas
...
+```{r, echo = FALSE, results = 'asis', fig.height=4}
+reasons_groupBar(df = qtl0002_params$dfListing, varGroupID = country, varCompreas = compreas, strGroupLabel = "Country", bSwapAxes = TRUE)
+```
+
 ## Discontinuation Listing
 ```{r, echo = FALSE}
-discontinuation_listing <- qtl0002_params$dfListing %>% 
-  select(subjid, invid, country, compreas) %>% 
+discontinuation_listing <- qtl0002_params$dfListing %>%
+  dplyr::filter(compyn %in% c("N")) %>%
```
Comment (samussiah) [inline inst/report/QTL0002.Rmd]: This needs to be configurable from the workflow. Otherwise the studies where discontinuation is represented by a `"Y"` need to be hard-coded. I kind of feel like adding `qtl000*_numerator` to `reporting_listings` is the simplest approach.

File: R/reasons_groupBar.R [hunk 11]
```diff
@@ -4,48 +4,85 @@
...
-reasons_groupBar <- function(df, varGroupID, varCompreas, strGroupLabel) {
+reasons_groupBar <- function(df, varGroupID, varCompreas, strGroupLabel, bSwapAxes = FALSE) {
+  var_sym <- rlang::ensym(varGroupID)
+  var_name <- rlang::as_string(var_sym)
+  compreas_sym <- rlang::ensym(varCompreas)
+  compreas_name <- rlang::as_string(compreas_sym)
+
   df_counts <- df %>%
-    dplyr::count({{varCompreas}}, {{varGroupID}}, name = "n")
+    dplyr::filter(.data[[compreas_name]] != "Completed/Ongoing") %>%
```
Comment (samussiah) [inline R/reasons_groupBar.R]: Just using a prefiltered numerator dataset makes sense here too.

**Review by samussiah — CHANGES_REQUESTED** [review]
Report looks great @zdz2101!  This PR still needs some work to consistently subset on participants in the numerator, and this subset should be defined and/or configurable in [`report_qtl`](https://github.com/Gilead-BioStats/gsm.qtl/blob/fix-90/inst/workflow/4_modules/report_qtl.yaml).

The most consistent approach is to apply the same subset to `lListings$qtl0002` as in `cou0006`/`kri0006`/`qtl0002` for premature discontinuation, and to `lListings$qtl0001` as in `cou0014`/`kri0014`/`qtl0001` for ineligibility. Ideally this "flag" is defined in the mapping layer but that will have to wait until a future release.  For now let's just apply the same subset in the module workflow rather than in the codebase or R markdown templates.

File: R/reasons_groupBar.R (hunk 11 above)
[the remark this answers is not in the document]
Comment (zdz2101) [reply R/reasons_groupBar.R]: More a mapping issue, safeguards already in place earlier in script/process

File: R/discontinuation_reasonBar.R [hunk 12]
```diff
@@ -6,7 +6,8 @@
 #' @returns A `plotly` object
 #' @export
 discontinuation_reasonBar <- function(df, varCompreas) {
-  reasonbar <- df %>%
+  reasonbar <- df  %>%
+    dplyr::filter(!!enexpr(varCompreas) != "Completed/Ongoing") %>%
     ggplot(., aes(y = {{varCompreas}},
```
[the remark this answers is not in the document]
Comment (zdz2101) [reply R/discontinuation_reasonBar.R:10]: More a mapping issue, safeguards already in place earlier in script/process

**Review by jonthegeek — APPROVED** [review]
The `ExpectUserAccepts()` usage looks right now. I'll also be sure to update {qcthat}'s installed action to include the fix here (along with some other similar things)!

**Review by samussiah — APPROVED** [review]
