### PR TITLE
Closes #70 addresses bugs found in eligibility report

### LINKED ISSUE #70: Address found bugs from eligibility report meeting
## Current Behavior
- Threshold & Deviation is showing up in Eligibiltiy Report
- ietest_cd hard set as 0.9 in site/source and country/source bars

## Expected Behavior
- eligibiilty report should not show anything from QTL
- remove the tooltip 0.9 piece 

## Steps to Reproduce

1.
2.
3.
4.

## QC Approach

In addition to standard QC (e.g., code reviews, automated checks) the following QC measures will be implemented:

[ ] Update existing Qualification/Unit Tests 
[ ] New Unit Tests

### PR DESCRIPTION
**Pull request by zdz2101**

### CODE REVIEW

File: R/criteria_groupBar.R [hunk 1]
```diff
@@ -8,34 +8,34 @@
...
-    filter(!is.na(ietestcd_concat) | Source == "Eligibility IPD") %>%
-    tidyr::separate_longer_delim(ietestcd_concat, ";;;") %>%
-    mutate(ietestcd_concat = ifelse(Source == "Eligibility IPD", "No EDC I/E available", ietestcd_concat)) %>%
-    pull(ietestcd_concat) %>%
-    unique() %>%
-    length()
-
   # Create plotly
-  plotly::ggplotly(group_criteria_bar, tooltip = c("y", "text"), h = calc_fig_size(n_rows = distinct_n_ie))
+  plotly::ggplotly(group_criteria_bar, tooltip = c("text"), h = calc_fig_size(n_rows = distinct_n_ie))
```
Comment (samussiah) [inline R/criteria_groupBar.R:48]: nice - this gets rid of that weird line in the tooltip

File: R/discontinuation_reasonBar.R [hunk 2]
```diff
@@ -6,6 +6,7 @@
 #' @export
 discontinuation_reasonBar <- function(df) {
   reasonbar <- df %>%
+    filter(compreas != "") %>%
```
Comment (samussiah) [inline R/discontinuation_reasonBar.R]: out-of-scope for this PR but the hard-coded column names need to be parameter-ized

File: R/Eligibility_Overview.R
Comment (samussiah) [inline R/Eligibility_Overview.R:1]: called over in `gsm.kri`

**Review by samussiah — APPROVED** [review]
Much nicer.

File: R/criteria_groupBar.R [hunk 3]
```diff
@@ -8,34 +8,34 @@
 #'
 #' @export
 criteria_groupBar <- function(df, varGroupID, strGroupLabel) {
+  var_sym  <- rlang::ensym(varGroupID)
```
Comment (samussiah) [inline R/criteria_groupBar.R:11]: alternative to `.data[[ varGroupID ]]`?

File: R/criteria_groupBar.R [hunk 4]
```diff
@@ -8,34 +8,34 @@
...
+  var_name <- rlang::as_string(var_sym)
```
Comment (samussiah) [inline R/criteria_groupBar.R:12]: how does this differ from `varGroupID`?

File: R/criteria_groupBar.R (hunk 3 above)
Comment (zdz2101) [reply R/criteria_groupBar.R:11]: more like I just didn't know how nicely it plays with `ggplot` codeblocks, and at the dawn of making these functions I was using the variable/symbol itself not a string (also because of ggplot friendliness)

File: R/reasons_groupBar.R [hunk 5]
```diff
@@ -1,39 +1,37 @@
...
-#' @param varGroupID A variable to make the stacked bar chart with, i.e. invid
+#' @param varGroupID A variable to make the stacked bar chart with, i.e. invid.
+#' @param varCompreas A variable to identify study completion/discontinuation reasons
 #' @param strGroupLabel A `string` to label the `varGroupID` in reference to axes, legend, footnotes.
 #'
 #' @returns A `plotly` object
 #'
 #' @export
-reasons_groupBar <- function(df, varGroupID, strGroupLabel) {
+reasons_groupBar <- function(df, varGroupID, varCompreas, strGroupLabel) {
```
Comment (zdz2101) [inline R/reasons_groupBar.R:11]: @samussiah the `compreas` stuff has been parameterized and added to the `QTL0002.Rmd` report

**Review by samussiah — APPROVED** [review]
Looks good to me!

File: R/Eligibility_Overview.R [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+                         strQTL) {
+  dfResults %>%
+    filter(
+      GroupLevel == "Study",
+      SnapshotDate == dSnapshot,
+      !(GroupID %in% c("Upper_funnel", "Flatline"))
+    ) %>%
+    mutate_at(c("Metric", "Numerator", "Denominator"), as.numeric) %>%
+    mutate(
+      qtlrate = paste0(as.character(round(Metric * 100, 3)), "%")
```
Comment (samussiah) [inline R/Eligibility_Overview.R]:
```suggestion
      qtlrate = paste0(as.character(round(Metric * 100, 1)), "%")
```

File: inst/report/QTL0002.Rmd [hunk 7]
```diff
@@ -32,17 +32,17 @@ discontinuation_groupBar(df = qtl0002_params$dfListing, varGroupID = country, st
 
 ### Reasons
 ```{r, echo = FALSE, results = 'asis', fig.height=4}
-discontinuation_reasonBar(df = qtl0002_params$dfListing)
+discontinuation_reasonBar(df = qtl0002_params$dfListing, varCompreas = compreas)
```
Comment (samussiah) [inline inst/report/QTL0002.Rmd:35]: huh, seems to work even though `compreas` isn't quoted...

**Review by samussiah — APPROVED** [review]
Charts look much better.  Will want to propagate workflows updates to `gsm.mapping` eventually, and I'd prefer to round the percentages to 1 decimal place.

**Comment by zdz2101** [comment]
> Charts look much better. Will want to propagate workflows updates to `gsm.mapping` eventually, and I'd prefer to round the percentages to 1 decimal place.

Workflow update is [here](https://github.com/Gilead-BioStats/gsm.mapping/pull/105)
